#!/bin/bash

sudo curl -s "https://raw.githubusercontent.com/learndevopsonline/labautomation/master/dry/common-functions.sh" -o /tmp/common-functions.sh
source /tmp/common-functions.sh

if [ "$1" == "clean" ]; then
  cd /tmp
  sudo -v &>/dev/null
  [ $? -eq 0 ] && sudo rm -rf labautomation || rm -rf labautomation
  echo $?
  echo -e "\e[1;35m Cleanup Succeeded\e[0m"
  exit 0
else
  if [ -d /tmp/labautomation ]; then
    cd /tmp/labautomation
    git pull &>/dev/null
    if [ $? -ne 0 ]; then
      cd ..
      sudo -v &>/dev/null
      [ $? -eq 0 ] && sudo rm -rf /tmp/lab* || rm -rf /tmp/lab*
      git clone https://github.com/learndevopsonline/labautomation.git /tmp/labautomation &>/dev/null
    fi
  else
    cd ..
    git clone https://github.com/learndevopsonline/labautomation.git /tmp/labautomation &>/dev/null
  fi
fi

if [ ! -f /tmp/labautomation/setup.sh ]; then
  echo -e "\e[1;33m💡💡 Hint! Try Using \e[0m\e[1m'sudo labauto clean'\e[0m"
  exit 1
fi
export AWS_PAGER=""
bash /tmp/labautomation/aws.sh $*
