#!/bin/bash

curl -s "https://raw.githubusercontent.com/linuxautomations/scripts/master/common-functions.sh" >/tmp/common-functions.sh
#source /root/scripts/common-functions.sh
source /tmp/common-functions.sh
## Checking Root User or not.
CheckRoot

## Checking SELINUX Enabled or not.
CheckSELinux

## Checking Firewall on the Server.
CheckFirewall &>/dev/null

## Supported OS's
# CentOS 7
if [ ! -f /etc/centos-release ]; then
	error "Curently this setup works only for CentOS Operating System"
	exit 1
fi

EL=$(rpm -q basesystem | sed -e 's/\./ /g' |xargs -n1 | grep el)
if [ "$EL" != "el7" ]; then
	error "Currently this setup works only for CentOS-7 OS"
	exit 1
fi

if [ "$1" == "clean" ]; then
  cd /tmp
  rm -rf labautomation
else
  if [ -d /tmp/labautomation ]; then
    cd /tmp/labautomation
    git pull &>/dev/null
  else
    git clone https://github.com/linuxautomations/labautomation.git /tmp/labautomation &>/dev/null
  fi
fi

sh /tmp/labautomation/setup.sh $*
