#!/bin/bash

# Script runs only in Workstation node where admin access is there.

aws s3 ls &>/dev/null
if [ $? -ne 0 ]; then
    echo "Access Denied"
    exit 1
fi

## Get Spot Requests

## Get Route53

## Get Parameter Store

## Get Secret Store
aws ssm describe-parameters | jq '.Parameters[].Name' >/tmp/list
aws ssm delete-parameters --names $(cat /tmp/list |xargs)
## Get KMS Keys

## Get S3 Buckets

## Get IAM Roles

## Get IAM Policies

